"use client";

import { useState, useCallback } from "react";
import AppShell from "@/app/components/layout/app-shell";
import CaseHeader from "@/app/components/investigation/case-header";
import InvestigationProgress from "@/app/components/investigation/investigation-progress";
import EvidenceSection from "@/app/components/investigation/evidence-section";
import RootCauseCard from "@/app/components/investigation/root-cause-card";
import ExecutionPath from "@/app/components/investigation/execution-path";
import ImpactAnalysis from "@/app/components/investigation/impact-analysis";
import FixRecommendation from "@/app/components/investigation/fix-recommendation";
import AITimeline from "@/app/components/investigation/ai-timeline";
import VerificationRunner from "@/app/components/investigation/verification-runner";
import ReproductionLab from "@/app/components/investigation/reproduction-lab";
import InvestigationIntelligence from "@/app/components/investigation/investigation-intelligence";
import {
  caseData,
  investigationStages,
  evidence,
  executionPath,
  impactMetrics,
  timeline,
} from "@/app/data/case-data";

export default function CaseReportPage() {
  const [isVerified, setIsVerified] = useState(false);

  const handleVerificationComplete = useCallback(() => {
    setIsVerified(true);
  }, []);

  const displayStatus = isVerified ? "Fix Verified" : caseData.status;
  const displayProgress = isVerified ? 100 : caseData.progress;
  const displayStages = isVerified
    ? investigationStages.map((s) => ({ ...s, status: "completed" as const }))
    : investigationStages;

  return (
    <AppShell>
      <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Case Header */}
        <div className="mb-6">
          <CaseHeader
            caseId={caseData.id}
            title={caseData.title}
            project={caseData.project}
            severity={caseData.severity}
            status={displayStatus}
            location={caseData.location}
          />
        </div>

        {/* Investigation Progress */}
        <div className="mb-6">
          <InvestigationProgress
            stages={displayStages}
            progress={displayProgress}
          />
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          {/* Left: Evidence + Root Cause */}
          <div className="lg:col-span-2 space-y-6">
            <EvidenceSection evidence={evidence} />
            <RootCauseCard
              description="An expired session token reaches validateSession() without being refreshed, causing the authentication middleware to reject the request."
              confidence={caseData.confidence}
              category="Authentication / Session Management"
              steps={[
                "Session token expires.",
                "Client does not refresh the token.",
                "validateSession() receives the expired token.",
                "Middleware returns 401.",
                "Dashboard request fails.",
              ]}
            />
          </div>

          {/* Right: Execution Path + Impact */}
          <div className="space-y-6">
            <ExecutionPath nodes={executionPath} />
            <ImpactAnalysis
              metrics={impactMetrics}
              description="Users with expired sessions may be returned to a failed dashboard state instead of being prompted to re-authenticate."
            />
          </div>
        </div>

        {/* Investigation Intelligence */}
        <div className="mb-6">
          <InvestigationIntelligence />
        </div>

        {/* Reproduction Lab */}
        <div className="mb-6">
          <ReproductionLab />
        </div>

        {/* Fix Recommendation */}
        <div className="mb-6">
          <FixRecommendation />
        </div>

        {/* AI Timeline + Verification */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
          <div className="lg:col-span-2">
            <AITimeline entries={timeline} />
          </div>
          <div>
            <VerificationRunner onComplete={handleVerificationComplete} />
          </div>
        </div>

        {/* Case Footer */}
        <div className="text-center py-6 border-t border-border">
          <div className="text-xs font-mono text-foreground-muted mb-1">
            CASE {caseData.id}
          </div>
          <div className="text-xs text-foreground-tertiary">
            Investigation generated by AI Bug Detective
          </div>
          <div className="text-[10px] text-foreground-muted mt-1">
            Mock investigation data
          </div>
        </div>
      </div>
    </AppShell>
  );
}
